ID_LEN = 16
MSG_CODE_LEN = 2
STATUS_LEN = 2
VERSION_LEN = 1
PAYLOAD_SIZE_LEN = 4
AES_KEY_LEN = 16

HEADERS_LEN = ID_LEN + VERSION_LEN + MSG_CODE_LEN + PAYLOAD_SIZE_LEN

NAME_LEN = 256
FILE_NAME_LEN = 256
PUBLIC_KEY_LEN = 160
FILE_SIZE_LEN = 4
CKSUM_LEN = 4
