CREATE TABLE FILES(
	ID VARCHAR(16) NOT NULL,
	FILENAME VARCHAR(256) NOT NULL,
	PATHNAME VARCHAR(256) NOT NULL,
	VERIFIED BOOK NOT NULL,

	FOREIGN KEY(ID)
		REFERENCES CLIENTS(ID)
			ON UPDATE CASCADE
			ON DELETE CASCADE
);