# lengths
ID_LEN = 16
MSG_CODE_LEN = 2
STATUS_LEN = 2
VERSION_LEN = 1
PAYLOAD_SIZE_LEN = 4

NAME_LEN = 256

# message code
REGISTER_MSGCODE = 1100
REGISTER_SUCC_STATUS = 2100
REGISTER_FAIL_STATUS = 2101

# system constants
VERSION = 3